# This is the netfortune-server config file in TOML format

# You have to comment the next line or set the option to false otherwise
# netfortune-server won't start
changed_config = false

[server]
port = 13
# specify which ip adresses the application should listen to
# 0.0.0.0 means all ip adresses, 127.0.0.1 only listen on localhost
listen_to = "127.0.0.1"

[fortunes]
# and fill a sqlite database with the contents.
base_folder = "/usr/share/fortune"
# specify which fortune files should not be parsed
blacklist = ""

[database]
location = "/var/lib/netfortune"
# create a statistics table to see which categories where querried most
create_stats = true

[logging]
logfile = "/var/log/netfortune"
# logfile maximum size in megabytes
logfile_max = 100
log_to_stdout = true
log_to_syslog = false
# possible values are debug, info, warning or error
minimum_loglevel = "warning"

